services:
  minio:
    container_name: minio
    image: minio/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    networks:
      - einsbym-network

  einsbym-storage:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: einsbym-storage
    depends_on:
      - minio
    ports:
      - 8080:8080
    env_file:
      - .env
    networks:
      - einsbym-network

networks:
  einsbym-network:
    external: true

volumes:
  minio_data:
    driver: local
