name: Build and Test

on:
  push:
    branches: ['develop', 'main', 'feature/*']
  pull_request:
    branches: ['develop', 'main', 'feature/*']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.18.1

      - name: Build
        run: go build -v ./...s

      - name: Test
        run: go test -v ./...
